### ISSUE TITLE
Reanimate playground

### ISSUE THREAD

**Issue by Hrxn** [reanimate/reanimate#96]
I know, this here just moved to the new location..
But the Playground is coming back, right? 😄 

Old URL does not work anymore: https://lemmih.github.io/reanimate/

**Comment by Lemmih** [comment]
The playground was fun but cost money to run. I would bring it back if a sponsor stepped up (either with a server or with $10 here on github).

**Comment by Hrxn** [comment]
Oh, I wasn't aware. I thought this was running on GitHub Pages, without, you know, incurring additional costs.

**Comment by Lemmih** [comment]
It should be possible to use Asterius or ghcjs to run reanimate in the browser (with a small server for compiling animations to JavaScript) . If so, I'll restore the playground.

**Comment by Lemmih** [comment]
Turns out it'll take up more resources to compile to JavaScript than to just render the SVGs. Will implement a non-javascript version instead.

Tasks:
- [ ] Full-screen playground.
- [ ] Embedded playground.
- [ ] Security:
    - [ ] Limit animation duration to 60 seconds
    - [ ] Limit CPU time (5 seconds if there's a queue, 30 seconds if there isn't)
    - [ ] Limit memory use
    - [ ] Limit disk space use (5 megs)
    - [ ] Kill and respawn ghci if anything goes wrong
- [ ] Use svgo to optimize generated svgs.
- [ ] Compress svgs to .svgz
- [ ] Automatically redeploy when changes are pushed to reanimate

**Comment by Lemmih** [comment]
@Hrxn Done! https://reanimate.github.io/reanimate/playground/

**Comment by Hrxn** [comment]
Thank you! I think it turned out great! 😄
